"""Digit-strip kNN OCR (``cv2.ml.KNearest``)."""
from __future__ import annotations

from kNN.digital.classifier import (
    DEFAULT_DIGIT_COUNT,
    DEFAULT_X0,
    DIGIT_CELL_H,
    DIGIT_CELL_W,
    CompactNumberPrediction,
    DigitClassifier,
    DigitPrediction,
    DigitTemplatePrediction,
    TemplateDigitClassifier,
    augment_glyph,
    build_training_matrices,
    estimate_digit_count,
    extract_labeled_compact_glyphs,
    extract_labeled_glyphs,
    glyph_to_feature,
    glyph_to_mask,
    parse_compact_number_text,
    parse_digit_count,
    render_synthetic_digit,
    save_dataset_meta,
    segment_compact_glyph_boxes,
    segment_digit_boxes,
)
from kNN.digital.loader import (
    COMPACT_NUMBER_PREPROCESS_TAGS,
    KNN_PREPROCESS_TAGS,
    get_classifier,
    get_compact_number_classifier,
    get_template_classifier,
    is_compact_number_preprocess,
    is_knn_preprocess,
    recognize_compact_number,
    recognize_compact_number_prediction,
    recognize_digits,
    recognize_digits_prediction,
    recognize_digits_template,
    recognize_digits_template_prediction,
)
from kNN.digital.paths import dataset_dir, digital_data_dir, model_path

__all__ = [
    "COMPACT_NUMBER_PREPROCESS_TAGS",
    "DEFAULT_DIGIT_COUNT",
    "DEFAULT_X0",
    "DIGIT_CELL_H",
    "DIGIT_CELL_W",
    "KNN_PREPROCESS_TAGS",
    "CompactNumberPrediction",
    "DigitClassifier",
    "DigitPrediction",
    "DigitTemplatePrediction",
    "TemplateDigitClassifier",
    "augment_glyph",
    "build_training_matrices",
    "dataset_dir",
    "digital_data_dir",
    "estimate_digit_count",
    "extract_labeled_compact_glyphs",
    "extract_labeled_glyphs",
    "get_classifier",
    "get_compact_number_classifier",
    "get_template_classifier",
    "glyph_to_feature",
    "glyph_to_mask",
    "is_compact_number_preprocess",
    "is_knn_preprocess",
    "model_path",
    "parse_compact_number_text",
    "parse_digit_count",
    "recognize_compact_number",
    "recognize_compact_number_prediction",
    "recognize_digits",
    "recognize_digits_prediction",
    "recognize_digits_template",
    "recognize_digits_template_prediction",
    "render_synthetic_digit",
    "save_dataset_meta",
    "segment_compact_glyph_boxes",
    "segment_digit_boxes",
]
