id: training_capacity_enhance_2h
name: Training Capacity Enhance (2h)
wiki_url: https://www.whiteoutsurvival.wiki/items/training-capacity-enhance-2h/
category: ''
description: Increases the Training Capacity and times for all Troops by 200% for
  2 hour(s)
sources:
- Increases the Training Capacity and times for all Troops by 200% for 2 hour(s)
