"""Emit 62 × 3 skeleton scenarios for hero upgrades.

Loops over ``db/heroes/index.yaml`` and writes one scenario per
``(hero, action)`` pair under ``scenarios/heroes/upgrade/``:

* ``level_up_<hid>.yaml``       — node ``page.heroes.<hid>``
* ``star_tier_up_<hid>.yaml``   — node ``page.heroes.<hid>``
* ``skill_up_<hid>.yaml``       — node ``page.heroes.<hid>``

Existing files are **not** overwritten — the generator is idempotent so
manual edits (steps you've filled in for an annotated hero) survive a
re-run. Pass ``--force`` to overwrite anyway.

The skeleton ``steps`` are commented out — uncomment after labelling
the matching button regions in area.json via the annotator UI.

Run: ``uv run python cmd/generate_upgrade_scenarios.py``
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

_ACTIONS = ("level_up", "star_tier_up", "skill_up")


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _skeleton_steps(action: str) -> str:
    """Commented-out step block — placeholder until annotator regions exist.

    Each action references in-game UI elements that need to be labelled:

    * ``level_up``     → tap the level-up button (long-press for x10), confirm.
    * ``star_tier_up`` → tap the star section, then the star-up button + confirm.
    * ``skill_up``     → tap the target skill icon, tap "Upgrade", confirm.
    """
    if action == "level_up":
        # ``page.heroes.unit.upgrade`` is the "Upgrade" label strip;
        # ``page.heroes.unit.upgrade_tap`` is the actual button. Both
        # already exist in area.json. We guard the click with
        # ``while_match: …upgrade, max: 1`` so the step is a no-op when
        # the button is missing (hero already maxed, off-screen, etc.).
        # After the tap, OCR re-reads the level + ``sync_hero_unit``
        # mirrors it into ``state.yaml`` so the optimizer sees the
        # progression immediately on the next solve.
        return (
            "  - while_match: page.heroes.unit.upgrade\n"
            "    max: 1\n"
            "    steps:\n"
            "      - click: page.heroes.unit.upgrade_tap\n"
            "      - wait: 0.8s\n"
            "      - ocr: page.heroes.unit.name\n"
            "        store: page.heroes.unit.name\n"
            "      - ocr: page.heroes.unit.level\n"
            "        type: integer\n"
            "        store: page.heroes.unit.level\n"
            "      - exec: sync_hero_unit\n"
        )
    if action == "star_tier_up":
        return (
            "  # TODO: label the in-game regions, then uncomment.\n"
            "  # - click: page.heroes.unit.btn.star_up\n"
            "  # - wait: 0.5s\n"
            "  # - click: page.heroes.unit.btn.star_up.confirm\n"
            "  # - wait: 1s\n"
            "  # - exec: sync_hero_unit\n"
        )
    if action == "skill_up":
        return (
            "  # TODO: label the in-game regions, then uncomment.\n"
            "  # The optimizer enqueues this scenario with a ``region`` field\n"
            "  # naming the target skill slot (e.g. page.heroes.unit.skill_1)\n"
            "  # — the click below should resolve through ${region} once the\n"
            "  # DSL is wired for param expansion. For now we leave a\n"
            "  # placeholder per-slot click commented out.\n"
            "  # - click: page.heroes.unit.skill_1\n"
            "  # - wait: 0.5s\n"
            "  # - click: page.heroes.unit.btn.skill_upgrade\n"
            "  # - wait: 0.5s\n"
            "  # - click: page.heroes.unit.btn.skill_upgrade.confirm\n"
            "  # - wait: 1s\n"
            "  # - exec: sync_hero_unit\n"
        )
    return "  # TODO\n"


def _scenario_yaml(*, name: str, node: str, action: str) -> str:
    """Action-aware YAML body. ``steps`` is a real list for actions whose
    region is already labelled (``level_up``); for the rest it's an
    empty list + commented-out TODO scaffold to be filled after labelling."""
    steps_block = _skeleton_steps(action)
    # When the template begins with a real list item ("- "), don't emit
    # ``steps: []`` — replace with the list itself. Otherwise keep the
    # explicit empty list so the YAML parses while we wait for regions.
    steps_yaml = (
        f"steps:\n{steps_block}"
        if steps_block.lstrip().startswith("- ")
        else f"steps: []\n{steps_block}"
    )
    return (
        f"enabled: true\n"
        f'name: "{name}"\n\n'
        f"# Generated by ``cmd/generate_upgrade_scenarios.py``. Pushed by the\n"
        f"# upgrade optimizer (``optimizer/dispatcher.py``). Steps for\n"
        f"# unlabeled actions stay commented until their regions are\n"
        f"# added via the annotator UI.\n\n"
        f"node: {node}\n\n"
        f"{steps_yaml}"
    )


def _name_for(action: str, hero_name: str) -> str:
    pretty = {
        "level_up": "⬆️ Level up",
        "star_tier_up": "⭐ Star tier up",
        "skill_up": "📘 Skill up",
    }.get(action, action)
    return f"{pretty} · {hero_name}"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Emit hero upgrade scenarios.")
    parser.add_argument(
        "--force", action="store_true", help="Overwrite existing files."
    )
    args = parser.parse_args(argv)

    repo = _repo_root()
    idx_path = repo / "db" / "heroes" / "index.yaml"
    if not idx_path.is_file():
        print("db/heroes/index.yaml not found", file=sys.stderr)
        return 2
    idx = yaml.safe_load(idx_path.read_text(encoding="utf-8")) or {}
    heroes = idx.get("heroes") or []

    out_dir = repo / "scenarios" / "heroes" / "upgrade"
    out_dir.mkdir(parents=True, exist_ok=True)

    created = 0
    skipped = 0
    for entry in heroes:
        if not isinstance(entry, dict):
            continue
        hid = str(entry.get("id") or "").strip()
        hname = str(entry.get("name") or "").strip() or hid
        if not hid:
            continue
        for action in _ACTIONS:
            path = out_dir / f"{action}_{hid}.yaml"
            if path.exists() and not args.force:
                skipped += 1
                continue
            body = _scenario_yaml(
                name=_name_for(action, hname),
                node=f"page.heroes.{hid}",
                action=action,
            )
            path.write_text(body, encoding="utf-8")
            created += 1

    print(f"created={created} skipped={skipped} dir={out_dir.relative_to(repo)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
