"""Locate (and tap) hero portraits on the ``heroes`` screen.

The heroes roster usually has more units than fit on screen (only ~12 cells
visible on 720×1280 BlueStacks). To open an arbitrary hero we:

1. Screencap the current frame.
2. Resize the wiki icon under ``db/assets/wiki/heroes/<id>/`` to 150×150 and
   run grayscale NCC (``cv2.matchTemplate``, ``TM_CCOEFF_NORMED``) inside the
   ``heroes.grid`` ROI from ``area.json``.
3. If the best peak ≥ ``threshold`` → tap its center.
4. Otherwise swipe up (revealing rows below the fold) and retry, up to
   ``max_swipes`` times.

The matcher is intentionally simple — single scale, no NMS, no color/edge
cap. Heroes have unique silhouettes and the wiki crop is the same square
~512×512 portrait as in-game, so plain NCC at the right scale separates
the target cleanly (matched ≥ 0.88 vs. unrelated ≤ 0.58 on the reference
frame). If we ever swap to a less consistent icon source, switch to
:func:`layout.template_match.match_template_in_search_roi_bbox_percent`.

``available`` (unlocked vs. shard-only) is detected from the mean HSV
**V** channel on the matched cell: unlocked cards are rendered bright
(V ≳ 140 on the reference frame) while locked cards sit at V ≲ 110.
"""
from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass
from functools import lru_cache
from typing import TYPE_CHECKING

import cv2
import numpy as np
import yaml

from config.paths import repo_root as default_repo_root
from layout.red_dot_detector import find_red_dots

if TYPE_CHECKING:
    from adb import BotActions
    from layout.types import Point

logger = logging.getLogger(__name__)

_TEMPLATE_PX = 150
_DEFAULT_THRESHOLD = 0.7
# Hero grid is a fixed 4-column layout with constant pitch on 720×1280
# BlueStacks frames. We exploit that by searching for each hero only
# inside a small per-cell window (template size + slack) instead of the
# full ``heroes.grid`` ROI — ~14× less heatmap area, and every match
# snaps to a specific cell so the mapping is unambiguous.
#
# All values are ROI-relative pixels and point at the top-left corner of
# the matched template (not the visible card frame, which extends a bit
# further around it). Calibrated from observed matches on
# ``references/page.heroes.png``.
# Generated by ``cmd/calibrate_heroes_grid.py`` from
# ``references/page.heroes.png`` — re-run that script if the heroes
# screen layout shifts (game update, different resolution, …).
_GRID_COLS = 4
_GRID_FIRST_ROW_Y = 65
_GRID_FIRST_COL_X = 13
_GRID_ROW_PITCH = 281
_GRID_COL_PITCH = 166
# Per-cell search slack absorbs visual drift (locked vs unlocked cards
# can render the portrait ±5 px off the perfect center).
_GRID_CELL_SEARCH_SLACK_PX = 30
_AVAILABLE_V_THRESHOLD = 140.0
"""Mean V (HSV) above this counts the cell as unlocked. Calibrated on
``references/page.heroes.png`` where unlocked cards measure V ≈ 178–193
and locked ones cluster at V ≈ 80–110."""
# --- Card-relative sub-region offsets ----------------------------------
# Hero cards are perfectly regular on the heroes grid: once the grid
# anchor is calibrated, every per-card region (portrait, level / shard
# badges, red dot, upgrade arrow) sits at a fixed ``(dx, dy, w, h)``
# offset from the card's top-left corner. We avoid recomputing from the
# matched template center because that drifts ±5 px between unlocked
# and locked renderings — anchoring on the calibrated cell origin keeps
# every sub-bbox identical for the same (row, col).
#
# Card footprint: pitches minus a 1-px gap to keep neighbouring cells
# visually distinct in debug overlays.
_CARD_W = _GRID_COL_PITCH - 1
_CARD_H = _GRID_ROW_PITCH - 1
# Hero portrait template position inside a card (matches the 150×150
# wiki / in-game icon).
_PORTRAIT_OFFSET = (9, 54, _TEMPLATE_PX, _TEMPLATE_PX)
# "Lv. X" badge on unlocked cards (locked cards show rarity stars at
# the same spot — caller must skip OCR when ``available`` is False).
_CARD_LEVEL_OFFSET = (24, 206, 120, 25)
# Shard-counter ("X/Y") badge on locked cards (unlocked → stars).
_CARD_SHARD_OFFSET = (24, 240, 120, 32)
# Notification badge at the top-right; can extend above ``card_top`` by
# a few px into the inter-card gap.
_CARD_RED_DOT_OFFSET = (124, -14, 60, 55)
# Green skill-upgrade arrow on the right edge of the Lv badge.
_CARD_UPGRADE_OFFSET = (119, 211, 30, 25)
_UPGRADE_GREEN_RATIO_MIN = 0.10
_UPGRADE_GREEN_LO = (45, 140, 140)
_UPGRADE_GREEN_HI = (85, 255, 255)
_DEFAULT_SWIPE_DELTA = 400
_DEFAULT_SWIPE_DURATION_MS = 400
_SWIPE_SETTLE_SECONDS = 0.6


@dataclass(frozen=True)
class HeroMatch:
    hero_id: str
    score: float
    xy: tuple[int, int]
    """Tap-center in global frame pixels."""
    cell: tuple[int, int]
    """``(row, col)`` index of the heroes-grid cell this match owns. Lets
    callers route through pre-defined cell tap regions instead of raw
    coordinates."""
    available: bool
    """True when the matched cell looks rendered in full color (unlocked)."""
    mean_v: float
    badge_bbox: tuple[int, int, int, int]
    """``(x, y, w, h)`` of the shard-counter badge on locked cards
    (``"X/Y"``), in global frame pixels. Empty / meaningless when
    ``available`` is True (the same spot shows rarity stars on unlocked
    cards)."""
    level_bbox: tuple[int, int, int, int]
    """``(x, y, w, h)`` of the ``"Lv. X"`` badge on unlocked cards (in
    global frame pixels). Meaningless when ``available`` is False — locked
    cards show rarity stars at this spot."""
    red_dot_bbox: tuple[int, int, int, int]
    """``(x, y, w, h)`` of the notification patch at the top-right corner
    of the card (in global frame pixels)."""
    has_red_dot: bool
    """True when :func:`layout.red_dot_detector.find_red_dots` reports any
    badge candidate inside ``red_dot_bbox`` on the captured frame."""
    upgrade_bbox: tuple[int, int, int, int]
    """``(x, y, w, h)`` of the green skill-upgrade arrow at the right edge
    of the Lv badge (in global frame pixels)."""
    upgrade_available: bool
    """True when bright saturated green fills ≥``_UPGRADE_GREEN_RATIO_MIN``
    of the upgrade patch on the captured frame — i.e. the game is showing
    the "skill upgrade ready" arrow."""



@lru_cache(maxsize=1)
def _heroes_grid_bbox_percent() -> dict[str, float]:
    area = json.loads((default_repo_root() / "area.json").read_text(encoding="utf-8"))
    for screen in area.get("screens", []):
        for region in screen.get("regions", []):
            if region.get("name") == "heroes.grid":
                return dict(region["bbox"])
    raise RuntimeError("heroes.grid region not found in area.json")


def _grid_roi_pixels(frame_h: int, frame_w: int) -> tuple[int, int, int, int]:
    bbox = _heroes_grid_bbox_percent()
    x = int(round(bbox["x"] / 100.0 * frame_w))
    y = int(round(bbox["y"] / 100.0 * frame_h))
    w = int(round(bbox["width"] / 100.0 * frame_w))
    h = int(round(bbox["height"] / 100.0 * frame_h))
    return x, y, w, h


@lru_cache(maxsize=128)
def _load_hero_template_gray(hero_id: str, scale_px: int = _TEMPLATE_PX) -> np.ndarray:
    icons_dir = default_repo_root() / "db" / "assets" / "wiki" / "heroes" / hero_id
    if not icons_dir.is_dir():
        raise FileNotFoundError(f"no wiki icons for hero {hero_id!r} at {icons_dir}")
    candidates = sorted(
        p for p in icons_dir.iterdir()
        if p.suffix.lower() in {".png", ".jpg", ".jpeg", ".webp"}
    )
    if not candidates:
        raise FileNotFoundError(f"no image files in {icons_dir}")
    icon = cv2.imread(str(candidates[0]))
    if icon is None:
        raise RuntimeError(f"cannot decode {candidates[0]}")
    gray = cv2.cvtColor(icon, cv2.COLOR_BGR2GRAY)
    return cv2.resize(gray, (scale_px, scale_px), interpolation=cv2.INTER_AREA)


@lru_cache(maxsize=1)
def _all_hero_ids() -> tuple[str, ...]:
    from config.heroes import hero_index_path

    idx_path = hero_index_path()
    raw = yaml.safe_load(idx_path.read_text(encoding="utf-8")) or {}
    heroes = raw.get("heroes", []) if isinstance(raw, dict) else []
    return tuple(
        str(h["id"]).strip()
        for h in heroes
        if isinstance(h, dict) and h.get("id")
    )


def _cell_upgrade_green_ratio(
    frame_bgr: np.ndarray, x: int, y: int, w: int, h: int
) -> float:
    """Fraction of bright-green pixels inside the upgrade-arrow patch."""
    x0 = max(0, x)
    y0 = max(0, y)
    x1 = min(frame_bgr.shape[1], x + w)
    y1 = min(frame_bgr.shape[0], y + h)
    if x1 <= x0 or y1 <= y0:
        return 0.0
    patch = frame_bgr[y0:y1, x0:x1]
    if patch.size == 0:
        return 0.0
    hsv = cv2.cvtColor(patch, cv2.COLOR_BGR2HSV)
    lo = np.array(_UPGRADE_GREEN_LO, dtype=np.uint8)
    hi = np.array(_UPGRADE_GREEN_HI, dtype=np.uint8)
    mask = cv2.inRange(hsv, lo, hi)
    return float(np.mean(mask > 0))


def _cell_has_red_dot(
    frame_bgr: np.ndarray, x: int, y: int, w: int, h: int
) -> bool:
    """True when the notification patch at ``(x, y, w, h)`` contains a red badge.

    The patch is clipped to the frame; an empty crop returns False. The full
    frame height is passed to ``find_red_dots`` so the radius bounds scale
    correctly (a small ROI would otherwise shrink the expected dot size)."""
    x0 = max(0, x)
    y0 = max(0, y)
    x1 = min(frame_bgr.shape[1], x + w)
    y1 = min(frame_bgr.shape[0], y + h)
    if x1 <= x0 or y1 <= y0:
        return False
    patch = frame_bgr[y0:y1, x0:x1]
    if patch.size == 0:
        return False
    return bool(find_red_dots(patch, image_h_for_norm=int(frame_bgr.shape[0])))


def _cell_mean_v(frame_bgr: np.ndarray, cx: int, cy: int, scale_px: int) -> float:
    """Mean V (HSV) over the ``scale_px × scale_px`` cell centred at ``(cx, cy)``."""
    half = scale_px // 2
    x0 = max(0, cx - half)
    y0 = max(0, cy - half)
    x1 = min(frame_bgr.shape[1], cx + half)
    y1 = min(frame_bgr.shape[0], cy + half)
    cell = frame_bgr[y0:y1, x0:x1]
    if cell.size == 0:
        return 0.0
    hsv = cv2.cvtColor(cell, cv2.COLOR_BGR2HSV)
    return float(np.mean(hsv[:, :, 2]))


def _cell_search_window(
    ri: int,
    ci: int,
    *,
    rx: int,
    ry: int,
    rw: int,
    rh: int,
    scale_px: int,
    slack: int = _GRID_CELL_SEARCH_SLACK_PX,
) -> tuple[int, int, int, int] | None:
    """Global-frame ``(x0, y0, x1, y1)`` for the search window of cell ``(ri, ci)``.

    Returns ``None`` when the cell falls (partially) outside the ROI — typical
    for the bottom row when the heroes screen hasn't been scrolled.
    """
    cell_tx = _GRID_FIRST_COL_X + ci * _GRID_COL_PITCH
    cell_ty = _GRID_FIRST_ROW_Y + ri * _GRID_ROW_PITCH
    sx0 = max(0, cell_tx - slack)
    sy0 = max(0, cell_ty - slack)
    sx1 = min(rw, cell_tx + scale_px + slack)
    sy1 = min(rh, cell_ty + scale_px + slack)
    if sx1 - sx0 < scale_px or sy1 - sy0 < scale_px:
        return None
    return (rx + sx0, ry + sy0, rx + sx1, ry + sy1)


def _num_grid_rows(rh: int, scale_px: int) -> int:
    """How many rows fully fit inside a ROI of height ``rh`` at this scale."""
    if rh < _GRID_FIRST_ROW_Y + scale_px:
        return 0
    return (rh - _GRID_FIRST_ROW_Y - scale_px) // _GRID_ROW_PITCH + 1


def _card_origin(
    ri: int, ci: int, *, rx: int, ry: int
) -> tuple[int, int]:
    """Global ``(x, y)`` of the card-frame top-left for cell ``(ri, ci)``.

    Subtracts the portrait offset (``_PORTRAIT_OFFSET``) from the template
    anchor so the result lands on the actual card border — that's the
    reference point all per-card sub-regions are anchored against.
    """
    portrait_dx, portrait_dy, _, _ = _PORTRAIT_OFFSET
    cx = rx + (_GRID_FIRST_COL_X - portrait_dx) + ci * _GRID_COL_PITCH
    cy = ry + (_GRID_FIRST_ROW_Y - portrait_dy) + ri * _GRID_ROW_PITCH
    return cx, cy


def _bbox_from_offset(
    origin: tuple[int, int], offset: tuple[int, int, int, int]
) -> tuple[int, int, int, int]:
    ox, oy = origin
    dx, dy, w, h = offset
    return (ox + dx, oy + dy, w, h)


def _hero_match_at(
    frame_bgr: np.ndarray,
    hero_id: str,
    score: float,
    cell: tuple[int, int],
    *,
    rx: int,
    ry: int,
    scale_px: int,
) -> HeroMatch:
    """Build a fully-populated :class:`HeroMatch` for cell ``(ri, ci)``.

    Every sub-region (level / shard / red dot / upgrade) is derived from
    the card origin via a fixed offset (see ``_CARD_*_OFFSET``), so the
    bboxes are deterministic per cell — no drift between unlocked and
    locked renderings.
    """
    ri, ci = cell
    card_xy = _card_origin(ri, ci, rx=rx, ry=ry)
    portrait_dx, portrait_dy, _, _ = _PORTRAIT_OFFSET
    cx = card_xy[0] + portrait_dx + scale_px // 2
    cy = card_xy[1] + portrait_dy + scale_px // 2
    mean_v = _cell_mean_v(frame_bgr, cx, cy, scale_px)
    badge_bbox = _bbox_from_offset(card_xy, _CARD_SHARD_OFFSET)
    level_bbox = _bbox_from_offset(card_xy, _CARD_LEVEL_OFFSET)
    red_dot_bbox = _bbox_from_offset(card_xy, _CARD_RED_DOT_OFFSET)
    upgrade_bbox = _bbox_from_offset(card_xy, _CARD_UPGRADE_OFFSET)
    has_dot = _cell_has_red_dot(frame_bgr, *red_dot_bbox)
    green_ratio = _cell_upgrade_green_ratio(frame_bgr, *upgrade_bbox)
    return HeroMatch(
        hero_id=hero_id,
        score=score,
        xy=(cx, cy),
        cell=(ri, ci),
        available=mean_v >= _AVAILABLE_V_THRESHOLD,
        mean_v=mean_v,
        badge_bbox=badge_bbox,
        level_bbox=level_bbox,
        red_dot_bbox=red_dot_bbox,
        has_red_dot=has_dot,
        upgrade_bbox=upgrade_bbox,
        upgrade_available=green_ratio >= _UPGRADE_GREEN_RATIO_MIN,
    )


def find_hero_in_frame(
    frame_bgr: np.ndarray,
    hero_id: str,
    *,
    threshold: float = _DEFAULT_THRESHOLD,
    scale_px: int = _TEMPLATE_PX,
) -> HeroMatch | None:
    """Return :class:`HeroMatch` for the best cell that contains ``hero_id``.

    Iterates the known 4×N grid layout (see ``_GRID_*`` constants) and runs
    a small per-cell NCC instead of one big sweep over the whole ROI.
    ``None`` when no cell scores above ``threshold``.
    """
    if frame_bgr.ndim != 3:
        raise ValueError("frame_bgr must be HxWx3 BGR")
    fh, fw = frame_bgr.shape[:2]
    rx, ry, rw, rh = _grid_roi_pixels(fh, fw)
    if rw < scale_px or rh < scale_px:
        return None
    template = _load_hero_template_gray(hero_id, scale_px)

    best_score = -1.0
    best_cell: tuple[int, int] | None = None
    for ri in range(_num_grid_rows(rh, scale_px)):
        for ci in range(_GRID_COLS):
            window = _cell_search_window(
                ri, ci, rx=rx, ry=ry, rw=rw, rh=rh, scale_px=scale_px
            )
            if window is None:
                continue
            wx0, wy0, wx1, wy1 = window
            patch_gray = cv2.cvtColor(
                frame_bgr[wy0:wy1, wx0:wx1], cv2.COLOR_BGR2GRAY
            )
            heat = cv2.matchTemplate(patch_gray, template, cv2.TM_CCOEFF_NORMED)
            _, max_val, _, _ = cv2.minMaxLoc(heat)
            score = float(max_val)
            if score > best_score:
                best_score = score
                best_cell = (ri, ci)

    if best_score < threshold or best_cell is None:
        return None
    return _hero_match_at(
        frame_bgr,
        hero_id,
        best_score,
        best_cell,
        rx=rx,
        ry=ry,
        scale_px=scale_px,
    )


def scan_grid_cells(
    frame_bgr: np.ndarray,
    hero_ids: tuple[str, ...] | None = None,
    *,
    threshold: float = _DEFAULT_THRESHOLD,
    scale_px: int = _TEMPLATE_PX,
) -> dict[tuple[int, int], HeroMatch]:
    """For each visible grid cell, pick the best-matching hero (or skip it).

    Each ``(row, col)`` is searched once: the cell's small window is
    grayscaled, and every candidate template's heat-map peak is compared
    inside that window. The winning hero owns the cell — no two heroes
    can claim the same physical position.
    """
    targets = hero_ids if hero_ids is not None else _all_hero_ids()
    if frame_bgr.ndim != 3:
        raise ValueError("frame_bgr must be HxWx3 BGR")
    fh, fw = frame_bgr.shape[:2]
    rx, ry, rw, rh = _grid_roi_pixels(fh, fw)
    if rw < scale_px or rh < scale_px:
        return {}

    # Preload all templates once so we don't re-resize per cell.
    templates: list[tuple[str, np.ndarray]] = []
    for hid in targets:
        try:
            templates.append((hid, _load_hero_template_gray(hid, scale_px)))
        except FileNotFoundError:
            continue

    cells: dict[tuple[int, int], HeroMatch] = {}
    for ri in range(_num_grid_rows(rh, scale_px)):
        for ci in range(_GRID_COLS):
            window = _cell_search_window(
                ri, ci, rx=rx, ry=ry, rw=rw, rh=rh, scale_px=scale_px
            )
            if window is None:
                continue
            wx0, wy0, wx1, wy1 = window
            patch_gray = cv2.cvtColor(
                frame_bgr[wy0:wy1, wx0:wx1], cv2.COLOR_BGR2GRAY
            )
            best_hid: str | None = None
            best_score = -1.0
            for hid, tpl in templates:
                heat = cv2.matchTemplate(patch_gray, tpl, cv2.TM_CCOEFF_NORMED)
                _, max_val, _, _ = cv2.minMaxLoc(heat)
                if max_val > best_score:
                    best_score = float(max_val)
                    best_hid = hid
            if best_hid is None or best_score < threshold:
                continue
            cells[(ri, ci)] = _hero_match_at(
                frame_bgr,
                best_hid,
                best_score,
                (ri, ci),
                rx=rx,
                ry=ry,
                scale_px=scale_px,
            )
    return cells


def scan_grid_frame(
    frame_bgr: np.ndarray,
    hero_ids: tuple[str, ...] | None = None,
    *,
    threshold: float = _DEFAULT_THRESHOLD,
    scale_px: int = _TEMPLATE_PX,
) -> dict[str, HeroMatch]:
    """Match every hero on the current frame, keyed by ``hero_id``.

    Thin wrapper around :func:`scan_grid_cells` — if two cells happen to
    pick the same hero (shouldn't, given the grid layout), the higher
    score wins. Most callers want this view; the per-cell map is exposed
    for tools that need positional context (e.g. the debug overlay).
    """
    cells = scan_grid_cells(
        frame_bgr, hero_ids, threshold=threshold, scale_px=scale_px
    )
    out: dict[str, HeroMatch] = {}
    for match in cells.values():
        prev = out.get(match.hero_id)
        if prev is None or match.score > prev.score:
            out[match.hero_id] = match
    return out


def find_and_tap_hero(
    actions: BotActions,
    instance_id: str,
    hero_id: str,
    *,
    threshold: float = _DEFAULT_THRESHOLD,
    max_swipes: int = 3,
    swipe_delta: int = _DEFAULT_SWIPE_DELTA,
    swipe_duration_ms: int = _DEFAULT_SWIPE_DURATION_MS,
    on_scan: callable[[dict[str, HeroMatch]], None] | None = None,
) -> bool:
    """Find ``hero_id`` on the heroes roster and tap its portrait.

    Captures the current frame, runs :func:`find_hero_in_frame`. If the hero
    is not visible, swipes the grid up (revealing rows below the fold) and
    retries up to ``max_swipes`` times. Returns ``True`` on tap.

    ``on_scan`` is invoked after every frame capture with the dict of
    *every* hero matched on that frame — handy for persisting which heroes
    were seen / unlocked into state.yaml while we're already scanning the
    grid for the target hero.

    Assumes the caller has already navigated to the ``heroes`` screen.
    """
    Point_t = _import_point_type()
    for attempt in range(max_swipes + 1):
        frame = actions.capture_screen_bgr(instance_id)
        if on_scan is not None:
            try:
                on_scan(scan_grid_frame(frame, threshold=threshold))
            except Exception:
                logger.exception(
                    "hero_grid_search: on_scan callback failed (continuing)"
                )
        hit = find_hero_in_frame(frame, hero_id, threshold=threshold)
        if hit is not None:
            cx, cy = hit.xy
            logger.info(
                "hero_grid_search: tap hero=%s instance=%s attempt=%d ncc=%.3f "
                "available=%s xy=(%d,%d)",
                hero_id, instance_id, attempt, hit.score, hit.available, cx, cy,
            )
            return bool(actions.tap(instance_id, Point_t(cx, cy)))
        if attempt == max_swipes:
            break
        logger.info(
            "hero_grid_search: hero=%s not visible (attempt=%d) — swiping up",
            hero_id, attempt,
        )
        if not actions.swipe_direction(
            instance_id, "up", swipe_delta, duration_ms=swipe_duration_ms
        ):
            logger.info("hero_grid_search: swipe blocked — aborting hero=%s", hero_id)
            return False
        time.sleep(_SWIPE_SETTLE_SECONDS)
    logger.info(
        "hero_grid_search: hero=%s not found after %d swipes",
        hero_id, max_swipes,
    )
    return False


def _import_point_type() -> type[Point]:
    # Lazy import keeps this module loadable without the ADB stack
    # (e.g. for unit tests that only call find_hero_in_frame on a fixture).
    from layout.types import Point as _Point
    return _Point
